name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    uses: StarCitizenTools/mediawiki-ci-workflows/.github/workflows/lint.yml@main
    with:
      lint-php: true
      lint-js: true
      lint-styles: true
      # lint-i18n: true
      lint-md: true

  test-js:
    uses: StarCitizenTools/mediawiki-ci-workflows/.github/workflows/test-js.yml@main

  test-php:
    uses: StarCitizenTools/mediawiki-ci-workflows/.github/workflows/test-php.yml@main
    with:
      project-type: extension
      project-name: IntegratedProfiles
      matrix: >-
        [
          {"mw":"REL1_45", "php":"8.3", "coverage":"xdebug", "experimental":false},
          {"mw":"REL1_46", "php":"8.5", "coverage":"none", "experimental":false},
          {"mw":"master", "php":"8.5", "coverage":"none", "experimental":true}
        ]